spring.application.name=backend

# Configuración del Servidor
server.port=8081

# Conexión a Base de Datos (PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Configuración de Kafka - PRODUCTOR
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuración de Kafka - CONSUMIDOR (Para descontar stock)
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer